# Generated by Django 4.0.4 on 2023-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Course_createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
